# File: .github/workflows/workflow.yml

name: Run Azure Login with OIDC
on: [push]

permissions:
  id-token: write
  contents: read
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Azure login
        uses: azure/login@v3
        with:
          client-id: ${{ secrets.612a33e7-c0a6-4f3a-834e-bdb67a9e56be }}
          tenant-id: ${{ secrets.f2f551c3-f50c-417d-ace1-3a248a8cfea5 }}
          subscription-id: ${{ secrets.810b80cd-13b1-49f3-8e17-30e8de385450_ID }}

      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show
